apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-seguridad-deploy
  labels:
    name: microservice-seguridad-deploy
    app: microservice
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: microservice-seguridad
      type: microservice
  template: 
    metadata:
      name: microservice-seguridad-pod
      labels: 
        app: microservice-seguridad
        type: microservice
    spec:
      containers:
      - name: microservice-seguridad-app
        image: ribarcaza/serviciosapiseguridad:v2.#{Build.BuildId}#
        ports:
          - containerPort: 80
        env:
          - name: MongoDb__ConnectionString
            value: mongodb://ribarcaza:123@mongo-service:27017