apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: microservice-libreria
    name: mongo-deploy
  name: mongo-deploy
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: microservice-libreria
      name: mongo-pod
    spec: 
      containers: 
        - 
          comand: 
            - /bin/bash
            - "-c"
          env: 
            - 
              name: MONGO_INITDB_ROOT_USERNAME
              value: ribarcaza
            - 
              name: MONGO_INITDB_ROOT_PASSWORD
              value: "123"
          image: "mongo:4.2.12"
          name: microservice-libreria-app
          ports: 
            - 
              containerPort: 27017
    template: 
      labels: 
        app: microservice-libreria
        name: mongo-pod
      metadata: ~
      name: mongo-pod
